version: '3.5'

services:
  db:
    image: mariadb
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    env_file: .env

  app:
    image: matomo:fpm-alpine
    restart: always
    depends_on:
      - "db"
    volumes:
#      - ./app_config:/var/www/html/config:rw
#      - ./app_logs:/var/www/html/logs
      - matomo:/var/www/html
    environment:
      - MATOMO_DATABASE_HOST=db
    env_file: .env

  web:
    image: nginx:alpine
    restart: always
    volumes:
      - matomo:/var/www/html:ro
      # see https://github.com/matomo-org/matomo-nginx
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - "app"
    ports:
      - 8080:80

volumes:
  matomo:
